default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  host: localhost
  port: 5432
  username: user
  password: pass
  database: repository

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
