version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ../../repository:/var/www/web
      - ../db:/var/www/db
      - /var/www/web/.bundle
      - /var/www/web/vendor
    environment:
      RAILS_ENV: development
    env_file:
      - ./dev.env
    command: bash -c "rm -f tmp/pids/*.pid && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./postgredata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./dev.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: repository
      PGDATA: /var/lib/postgresql/data/pgdata